# syntax=docker/dockerfile:1
FROM continuumio/anaconda3
WORKDIR /code
RUN conda create -n emo python=3.6 -y
# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "emo", "/bin/bash", "-c"]
RUN conda install -c anaconda markdown -y
RUN conda install -c conda-forge requests-html -y
